version: "3.9"
services:
  event-booking-db:
    image: postgres
    restart: always
    container_name: event-booking-db
    ports:
      - 5435:5432
    environment:
      POSTGRES_PASSWORD: example
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres

volumes:
  postgres:
