@baseUrl = http://localhost:8080

# @name login
POST {{baseUrl}}/login HTTP/1.1
Content-Type: application/json

{
  "email": "test@email.com",
  "password": "never ever"
}


###
@authToken = {{login.response.body.token}}

POST {{baseUrl}}/events HTTP/1.1
Authorization: {{authToken}}
Content-Type: application/json

{
  "name": "Test Event",
  "description": "A Test Event",
  "location": "A Test Location",
  "dateTime": "2025-01-01T15:30:00Z"
}

###

GET {{baseUrl}}/events HTTP/1.1
